//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantEntities1 : DbContext
    {
        public RestaurantEntities1()
            : base("name=RestaurantEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergen> Alergens { get; set; }
        public virtual DbSet<AlergenPreparat> AlergenPreparats { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Comanda> Comandas { get; set; }
        public virtual DbSet<Cont> Conts { get; set; }
        public virtual DbSet<DetaliiCont> DetaliiConts { get; set; }
        public virtual DbSet<Fotografie> Fotografies { get; set; }
        public virtual DbSet<Meniu> Menius { get; set; }
        public virtual DbSet<MeniuComanda> MeniuComandas { get; set; }
        public virtual DbSet<MeniuPreparat> MeniuPreparats { get; set; }
        public virtual DbSet<Preparat> Preparats { get; set; }
        public virtual DbSet<PreparatComanda> PreparatComandas { get; set; }
        public virtual DbSet<StatusComanda> StatusComandas { get; set; }
        public virtual DbSet<StatusulComenzii> StatusulComenziis { get; set; }
    
        public virtual int AdaugareAlergen(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareAlergen", denumireParameter);
        }
    
        public virtual int AdaugareAlergenPreparat(string denumireAlergen, string denumirePreparat)
        {
            var denumireAlergenParameter = denumireAlergen != null ?
                new ObjectParameter("denumireAlergen", denumireAlergen) :
                new ObjectParameter("denumireAlergen", typeof(string));
    
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareAlergenPreparat", denumireAlergenParameter, denumirePreparatParameter);
        }
    
        public virtual int AdaugareCategorie(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareCategorie", denumireParameter);
        }
    
        public virtual int AdaugareComanda(Nullable<double> discount, string email, Nullable<System.DateTime> date)
        {
            var discountParameter = discount.HasValue ?
                new ObjectParameter("discount", discount) :
                new ObjectParameter("discount", typeof(double));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareComanda", discountParameter, emailParameter, dateParameter);
        }
    
        public virtual int AdaugareCont(string email, string parola, string statut)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var parolaParameter = parola != null ?
                new ObjectParameter("parola", parola) :
                new ObjectParameter("parola", typeof(string));
    
            var statutParameter = statut != null ?
                new ObjectParameter("statut", statut) :
                new ObjectParameter("statut", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareCont", emailParameter, parolaParameter, statutParameter);
        }
    
        public virtual int AdaugareDetaliiCont(string nume, string prenume, string adresa, Nullable<int> telefon, string email)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("prenume", prenume) :
                new ObjectParameter("prenume", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("adresa", adresa) :
                new ObjectParameter("adresa", typeof(string));
    
            var telefonParameter = telefon.HasValue ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareDetaliiCont", numeParameter, prenumeParameter, adresaParameter, telefonParameter, emailParameter);
        }
    
        public virtual int AdaugareMeniu(string denumire, Nullable<double> pret, Nullable<double> reducere)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var pretParameter = pret.HasValue ?
                new ObjectParameter("pret", pret) :
                new ObjectParameter("pret", typeof(double));
    
            var reducereParameter = reducere.HasValue ?
                new ObjectParameter("reducere", reducere) :
                new ObjectParameter("reducere", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareMeniu", denumireParameter, pretParameter, reducereParameter);
        }
    
        public virtual int AdaugareMeniuInComanda(Nullable<int> comanda, string denumiremeniu, Nullable<double> cantitate)
        {
            var comandaParameter = comanda.HasValue ?
                new ObjectParameter("comanda", comanda) :
                new ObjectParameter("comanda", typeof(int));
    
            var denumiremeniuParameter = denumiremeniu != null ?
                new ObjectParameter("denumiremeniu", denumiremeniu) :
                new ObjectParameter("denumiremeniu", typeof(string));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareMeniuInComanda", comandaParameter, denumiremeniuParameter, cantitateParameter);
        }
    
        public virtual int AdaugarePoza(string foto_path, Nullable<int> id_preparat)
        {
            var foto_pathParameter = foto_path != null ?
                new ObjectParameter("foto_path", foto_path) :
                new ObjectParameter("foto_path", typeof(string));
    
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugarePoza", foto_pathParameter, id_preparatParameter);
        }
    
        public virtual int AdaugarePreparat(string denumire, Nullable<double> pret, Nullable<double> cantitate, Nullable<double> cantitate_totala, Nullable<int> id_categorie)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var pretParameter = pret.HasValue ?
                new ObjectParameter("pret", pret) :
                new ObjectParameter("pret", typeof(double));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(double));
    
            var cantitate_totalaParameter = cantitate_totala.HasValue ?
                new ObjectParameter("cantitate_totala", cantitate_totala) :
                new ObjectParameter("cantitate_totala", typeof(double));
    
            var id_categorieParameter = id_categorie.HasValue ?
                new ObjectParameter("id_categorie", id_categorie) :
                new ObjectParameter("id_categorie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugarePreparat", denumireParameter, pretParameter, cantitateParameter, cantitate_totalaParameter, id_categorieParameter);
        }
    
        public virtual int AdaugarePreparatCategorie(string denumireCategorie, string denumirePreparat, Nullable<double> pretPreparat, Nullable<double> cantPreparat, Nullable<double> cantTotalaPreparat)
        {
            var denumireCategorieParameter = denumireCategorie != null ?
                new ObjectParameter("denumireCategorie", denumireCategorie) :
                new ObjectParameter("denumireCategorie", typeof(string));
    
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            var pretPreparatParameter = pretPreparat.HasValue ?
                new ObjectParameter("pretPreparat", pretPreparat) :
                new ObjectParameter("pretPreparat", typeof(double));
    
            var cantPreparatParameter = cantPreparat.HasValue ?
                new ObjectParameter("cantPreparat", cantPreparat) :
                new ObjectParameter("cantPreparat", typeof(double));
    
            var cantTotalaPreparatParameter = cantTotalaPreparat.HasValue ?
                new ObjectParameter("cantTotalaPreparat", cantTotalaPreparat) :
                new ObjectParameter("cantTotalaPreparat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugarePreparatCategorie", denumireCategorieParameter, denumirePreparatParameter, pretPreparatParameter, cantPreparatParameter, cantTotalaPreparatParameter);
        }
    
        public virtual int AdaugarePreparatInComanda(Nullable<int> comanda, string denPreparat, Nullable<double> cantitate)
        {
            var comandaParameter = comanda.HasValue ?
                new ObjectParameter("comanda", comanda) :
                new ObjectParameter("comanda", typeof(int));
    
            var denPreparatParameter = denPreparat != null ?
                new ObjectParameter("denPreparat", denPreparat) :
                new ObjectParameter("denPreparat", typeof(string));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugarePreparatInComanda", comandaParameter, denPreparatParameter, cantitateParameter);
        }
    
        public virtual int AdaugarePreparatInMeniu(string denumireMeniu, string denumirePreparat, Nullable<double> cantitatePreparat)
        {
            var denumireMeniuParameter = denumireMeniu != null ?
                new ObjectParameter("denumireMeniu", denumireMeniu) :
                new ObjectParameter("denumireMeniu", typeof(string));
    
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            var cantitatePreparatParameter = cantitatePreparat.HasValue ?
                new ObjectParameter("cantitatePreparat", cantitatePreparat) :
                new ObjectParameter("cantitatePreparat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugarePreparatInMeniu", denumireMeniuParameter, denumirePreparatParameter, cantitatePreparatParameter);
        }
    
        public virtual int AdaugareStatus(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdaugareStatus", denumireParameter);
        }
    
        public virtual ObjectResult<AfisareAlergen_Result> AfisareAlergen(Nullable<int> id_alergen)
        {
            var id_alergenParameter = id_alergen.HasValue ?
                new ObjectParameter("id_alergen", id_alergen) :
                new ObjectParameter("id_alergen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareAlergen_Result>("AfisareAlergen", id_alergenParameter);
        }
    
        public virtual ObjectResult<AfisareAlergeni_Result> AfisareAlergeni()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareAlergeni_Result>("AfisareAlergeni");
        }
    
        public virtual ObjectResult<AfisareCategorieDupaID_Result> AfisareCategorieDupaID(Nullable<int> id_categorie)
        {
            var id_categorieParameter = id_categorie.HasValue ?
                new ObjectParameter("id_categorie", id_categorie) :
                new ObjectParameter("id_categorie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareCategorieDupaID_Result>("AfisareCategorieDupaID", id_categorieParameter);
        }
    
        public virtual ObjectResult<AfisareCategoriePreparat_Result> AfisareCategoriePreparat(string denumirePreparat)
        {
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareCategoriePreparat_Result>("AfisareCategoriePreparat", denumirePreparatParameter);
        }
    
        public virtual ObjectResult<AfisareCategorii_Result> AfisareCategorii()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareCategorii_Result>("AfisareCategorii");
        }
    
        public virtual ObjectResult<AfisareComenziCont_Result> AfisareComenziCont(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareComenziCont_Result>("AfisareComenziCont", emailParameter);
        }
    
        public virtual ObjectResult<AfisareDetaliiComandaDupaEmail_Result> AfisareDetaliiComandaDupaEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareDetaliiComandaDupaEmail_Result>("AfisareDetaliiComandaDupaEmail", emailParameter);
        }
    
        public virtual ObjectResult<AfisareDetaliiComandaDupaIdComanda_Result> AfisareDetaliiComandaDupaIdComanda(Nullable<int> idcomanda)
        {
            var idcomandaParameter = idcomanda.HasValue ?
                new ObjectParameter("idcomanda", idcomanda) :
                new ObjectParameter("idcomanda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareDetaliiComandaDupaIdComanda_Result>("AfisareDetaliiComandaDupaIdComanda", idcomandaParameter);
        }
    
        public virtual ObjectResult<AfisareDetaliiCont_Result> AfisareDetaliiCont(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareDetaliiCont_Result>("AfisareDetaliiCont", emailParameter);
        }
    
        public virtual ObjectResult<AfisareListaAlergeniPreparat_Result> AfisareListaAlergeniPreparat(string denumirePreparat)
        {
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareListaAlergeniPreparat_Result>("AfisareListaAlergeniPreparat", denumirePreparatParameter);
        }
    
        public virtual ObjectResult<AfisareMeniuriComanda_Result> AfisareMeniuriComanda(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisareMeniuriComanda_Result>("AfisareMeniuriComanda", emailParameter);
        }
    
        public virtual ObjectResult<AfisarePreparatDupaCategorie_Result> AfisarePreparatDupaCategorie(string denumireCategorie)
        {
            var denumireCategorieParameter = denumireCategorie != null ?
                new ObjectParameter("denumireCategorie", denumireCategorie) :
                new ObjectParameter("denumireCategorie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisarePreparatDupaCategorie_Result>("AfisarePreparatDupaCategorie", denumireCategorieParameter);
        }
    
        public virtual ObjectResult<AfisarePreparatDupaDenumire_Result> AfisarePreparatDupaDenumire(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisarePreparatDupaDenumire_Result>("AfisarePreparatDupaDenumire", denumireParameter);
        }
    
        public virtual ObjectResult<AfisarePreparatDupaID_Result> AfisarePreparatDupaID(Nullable<int> id_preparat)
        {
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisarePreparatDupaID_Result>("AfisarePreparatDupaID", id_preparatParameter);
        }
    
        public virtual ObjectResult<AfisarePreparate_Result> AfisarePreparate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisarePreparate_Result>("AfisarePreparate");
        }
    
        public virtual int AfisarePreparateComanda(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AfisarePreparateComanda", emailParameter);
        }
    
        public virtual ObjectResult<AfisarePreparateDinMeniu_Result> AfisarePreparateDinMeniu(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisarePreparateDinMeniu_Result>("AfisarePreparateDinMeniu", denumireParameter);
        }
    
        public virtual ObjectResult<AfisarePreparateMeniu_Result> AfisarePreparateMeniu(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfisarePreparateMeniu_Result>("AfisarePreparateMeniu", denumireParameter);
        }
    
        public virtual int AplicaReducereMeniu(string denumire, Nullable<double> reducere)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var reducereParameter = reducere.HasValue ?
                new ObjectParameter("reducere", reducere) :
                new ObjectParameter("reducere", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AplicaReducereMeniu", denumireParameter, reducereParameter);
        }
    
        public virtual ObjectResult<CautaMeniu_Result> CautaMeniu(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CautaMeniu_Result>("CautaMeniu", denumireParameter);
        }
    
        public virtual ObjectResult<CautaPreparat_Result> CautaPreparat(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CautaPreparat_Result>("CautaPreparat", denumireParameter);
        }
    
        public virtual int LegaturaMeniuComanda(Nullable<int> id_meniu, Nullable<int> id_comanda, Nullable<int> nrBucati)
        {
            var id_meniuParameter = id_meniu.HasValue ?
                new ObjectParameter("id_meniu", id_meniu) :
                new ObjectParameter("id_meniu", typeof(int));
    
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var nrBucatiParameter = nrBucati.HasValue ?
                new ObjectParameter("nrBucati", nrBucati) :
                new ObjectParameter("nrBucati", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LegaturaMeniuComanda", id_meniuParameter, id_comandaParameter, nrBucatiParameter);
        }
    
        public virtual int LegaturaPreparatAlergen(Nullable<int> id_preparat, Nullable<int> id_alergen)
        {
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            var id_alergenParameter = id_alergen.HasValue ?
                new ObjectParameter("id_alergen", id_alergen) :
                new ObjectParameter("id_alergen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LegaturaPreparatAlergen", id_preparatParameter, id_alergenParameter);
        }
    
        public virtual int LegaturaPreparatComanda(Nullable<int> id_preparat, Nullable<int> id_comanda, Nullable<int> nrBucati)
        {
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var nrBucatiParameter = nrBucati.HasValue ?
                new ObjectParameter("nrBucati", nrBucati) :
                new ObjectParameter("nrBucati", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LegaturaPreparatComanda", id_preparatParameter, id_comandaParameter, nrBucatiParameter);
        }
    
        public virtual int LegaturaPreparatMeniu(Nullable<int> id_preparat, Nullable<int> id_meniu, Nullable<double> cantitate)
        {
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            var id_meniuParameter = id_meniu.HasValue ?
                new ObjectParameter("id_meniu", id_meniu) :
                new ObjectParameter("id_meniu", typeof(int));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LegaturaPreparatMeniu", id_preparatParameter, id_meniuParameter, cantitateParameter);
        }
    
        public virtual int LegaturaStatusComanda(Nullable<int> id_comanda, Nullable<int> id_status)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var id_statusParameter = id_status.HasValue ?
                new ObjectParameter("id_status", id_status) :
                new ObjectParameter("id_status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LegaturaStatusComanda", id_comandaParameter, id_statusParameter);
        }
    
        public virtual int ModificaAlergen(string denumire, string denumireNoua)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var denumireNouaParameter = denumireNoua != null ?
                new ObjectParameter("denumireNoua", denumireNoua) :
                new ObjectParameter("denumireNoua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaAlergen", denumireParameter, denumireNouaParameter);
        }
    
        public virtual int ModificaCategorie(string denumire, string denumireNoua)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var denumireNouaParameter = denumireNoua != null ?
                new ObjectParameter("denumireNoua", denumireNoua) :
                new ObjectParameter("denumireNoua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaCategorie", denumireParameter, denumireNouaParameter);
        }
    
        public virtual int ModificaMeniu(string denumire, Nullable<double> reducere)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var reducereParameter = reducere.HasValue ?
                new ObjectParameter("reducere", reducere) :
                new ObjectParameter("reducere", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaMeniu", denumireParameter, reducereParameter);
        }
    
        public virtual int ModificaNumeMeniu(string denumire, string denumireNoua)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var denumireNouaParameter = denumireNoua != null ?
                new ObjectParameter("denumireNoua", denumireNoua) :
                new ObjectParameter("denumireNoua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaNumeMeniu", denumireParameter, denumireNouaParameter);
        }
    
        public virtual int ModificaPreparat(Nullable<int> id, string denPreparat, Nullable<double> pret, Nullable<double> cantitate, Nullable<double> cantitate_totala, Nullable<int> id_categorie)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var denPreparatParameter = denPreparat != null ?
                new ObjectParameter("denPreparat", denPreparat) :
                new ObjectParameter("denPreparat", typeof(string));
    
            var pretParameter = pret.HasValue ?
                new ObjectParameter("pret", pret) :
                new ObjectParameter("pret", typeof(double));
    
            var cantitateParameter = cantitate.HasValue ?
                new ObjectParameter("cantitate", cantitate) :
                new ObjectParameter("cantitate", typeof(double));
    
            var cantitate_totalaParameter = cantitate_totala.HasValue ?
                new ObjectParameter("cantitate_totala", cantitate_totala) :
                new ObjectParameter("cantitate_totala", typeof(double));
    
            var id_categorieParameter = id_categorie.HasValue ?
                new ObjectParameter("id_categorie", id_categorie) :
                new ObjectParameter("id_categorie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaPreparat", idParameter, denPreparatParameter, pretParameter, cantitateParameter, cantitate_totalaParameter, id_categorieParameter);
        }
    
        public virtual int ModificaPretPreparatInMeniu(string denumireMeniu, string denumirePreparat, Nullable<double> cantitateNoua)
        {
            var denumireMeniuParameter = denumireMeniu != null ?
                new ObjectParameter("denumireMeniu", denumireMeniu) :
                new ObjectParameter("denumireMeniu", typeof(string));
    
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            var cantitateNouaParameter = cantitateNoua.HasValue ?
                new ObjectParameter("cantitateNoua", cantitateNoua) :
                new ObjectParameter("cantitateNoua", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaPretPreparatInMeniu", denumireMeniuParameter, denumirePreparatParameter, cantitateNouaParameter);
        }
    
        public virtual int ModificareAlergen(string denumireCurenta, string denumireNoua)
        {
            var denumireCurentaParameter = denumireCurenta != null ?
                new ObjectParameter("denumireCurenta", denumireCurenta) :
                new ObjectParameter("denumireCurenta", typeof(string));
    
            var denumireNouaParameter = denumireNoua != null ?
                new ObjectParameter("denumireNoua", denumireNoua) :
                new ObjectParameter("denumireNoua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificareAlergen", denumireCurentaParameter, denumireNouaParameter);
        }
    
        public virtual int ModificarePretComanda(Nullable<int> icomanda, string denumirePreparat, Nullable<double> cantitatePreparat)
        {
            var icomandaParameter = icomanda.HasValue ?
                new ObjectParameter("icomanda", icomanda) :
                new ObjectParameter("icomanda", typeof(int));
    
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            var cantitatePreparatParameter = cantitatePreparat.HasValue ?
                new ObjectParameter("cantitatePreparat", cantitatePreparat) :
                new ObjectParameter("cantitatePreparat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarePretComanda", icomandaParameter, denumirePreparatParameter, cantitatePreparatParameter);
        }
    
        public virtual int ModificarePretComandaMeniu(Nullable<int> icomanda, string denMeniu, Nullable<double> cantitatePreparat)
        {
            var icomandaParameter = icomanda.HasValue ?
                new ObjectParameter("icomanda", icomanda) :
                new ObjectParameter("icomanda", typeof(int));
    
            var denMeniuParameter = denMeniu != null ?
                new ObjectParameter("denMeniu", denMeniu) :
                new ObjectParameter("denMeniu", typeof(string));
    
            var cantitatePreparatParameter = cantitatePreparat.HasValue ?
                new ObjectParameter("cantitatePreparat", cantitatePreparat) :
                new ObjectParameter("cantitatePreparat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarePretComandaMeniu", icomandaParameter, denMeniuParameter, cantitatePreparatParameter);
        }
    
        public virtual int ModificarePretMeniu(string denMeniu, string denPreparat, Nullable<double> cant)
        {
            var denMeniuParameter = denMeniu != null ?
                new ObjectParameter("denMeniu", denMeniu) :
                new ObjectParameter("denMeniu", typeof(string));
    
            var denPreparatParameter = denPreparat != null ?
                new ObjectParameter("denPreparat", denPreparat) :
                new ObjectParameter("denPreparat", typeof(string));
    
            var cantParameter = cant.HasValue ?
                new ObjectParameter("cant", cant) :
                new ObjectParameter("cant", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarePretMeniu", denMeniuParameter, denPreparatParameter, cantParameter);
        }
    
        public virtual int SelectareAlergen(string alergenPrimit, ObjectParameter id_alergen)
        {
            var alergenPrimitParameter = alergenPrimit != null ?
                new ObjectParameter("alergenPrimit", alergenPrimit) :
                new ObjectParameter("alergenPrimit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectareAlergen", alergenPrimitParameter, id_alergen);
        }
    
        public virtual int SelectareAlergenPreparat(Nullable<int> id_alergen, Nullable<int> id_preparat, ObjectParameter id_alergenPreparat)
        {
            var id_alergenParameter = id_alergen.HasValue ?
                new ObjectParameter("id_alergen", id_alergen) :
                new ObjectParameter("id_alergen", typeof(int));
    
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectareAlergenPreparat", id_alergenParameter, id_preparatParameter, id_alergenPreparat);
        }
    
        public virtual int SelectareCantitateProdus(string denumireProdus, ObjectParameter cantitateP)
        {
            var denumireProdusParameter = denumireProdus != null ?
                new ObjectParameter("denumireProdus", denumireProdus) :
                new ObjectParameter("denumireProdus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectareCantitateProdus", denumireProdusParameter, cantitateP);
        }
    
        public virtual int SelectareCantProdusInMeniu(string id_preparat, ObjectParameter cantitateInMeniu)
        {
            var id_preparatParameter = id_preparat != null ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectareCantProdusInMeniu", id_preparatParameter, cantitateInMeniu);
        }
    
        public virtual int SelectareCategorie(string categoriePrimita, ObjectParameter id_categorie)
        {
            var categoriePrimitaParameter = categoriePrimita != null ?
                new ObjectParameter("categoriePrimita", categoriePrimita) :
                new ObjectParameter("categoriePrimita", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectareCategorie", categoriePrimitaParameter, id_categorie);
        }
    
        public virtual int SelectareCont(string emailPrimit, ObjectParameter id_cont)
        {
            var emailPrimitParameter = emailPrimit != null ?
                new ObjectParameter("emailPrimit", emailPrimit) :
                new ObjectParameter("emailPrimit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectareCont", emailPrimitParameter, id_cont);
        }
    
        public virtual int SelectareMeniu(string meniuPrimit, ObjectParameter id_meniu)
        {
            var meniuPrimitParameter = meniuPrimit != null ?
                new ObjectParameter("meniuPrimit", meniuPrimit) :
                new ObjectParameter("meniuPrimit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectareMeniu", meniuPrimitParameter, id_meniu);
        }
    
        public virtual int SelectarePreparat(string preparatPrimit, ObjectParameter id_preparat)
        {
            var preparatPrimitParameter = preparatPrimit != null ?
                new ObjectParameter("preparatPrimit", preparatPrimit) :
                new ObjectParameter("preparatPrimit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectarePreparat", preparatPrimitParameter, id_preparat);
        }
    
        public virtual int SelectarePretMeniu(string denumireMeniu, ObjectParameter pret_meniu)
        {
            var denumireMeniuParameter = denumireMeniu != null ?
                new ObjectParameter("denumireMeniu", denumireMeniu) :
                new ObjectParameter("denumireMeniu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectarePretMeniu", denumireMeniuParameter, pret_meniu);
        }
    
        public virtual int SelectarePretProdus(string denumireProdus, ObjectParameter pret_produs)
        {
            var denumireProdusParameter = denumireProdus != null ?
                new ObjectParameter("denumireProdus", denumireProdus) :
                new ObjectParameter("denumireProdus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectarePretProdus", denumireProdusParameter, pret_produs);
        }
    
        public virtual int StergeAlergen(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeAlergen", denumireParameter);
        }
    
        public virtual int StergeAlergenDupaID(Nullable<int> alergen, Nullable<int> preparat)
        {
            var alergenParameter = alergen.HasValue ?
                new ObjectParameter("alergen", alergen) :
                new ObjectParameter("alergen", typeof(int));
    
            var preparatParameter = preparat.HasValue ?
                new ObjectParameter("preparat", preparat) :
                new ObjectParameter("preparat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeAlergenDupaID", alergenParameter, preparatParameter);
        }
    
        public virtual int StergeCategorie(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeCategorie", denumireParameter);
        }
    
        public virtual int StergeMeniu(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeMeniu", denumireParameter);
        }
    
        public virtual int StergePoza(Nullable<int> id_foto, Nullable<int> id_preparat)
        {
            var id_fotoParameter = id_foto.HasValue ?
                new ObjectParameter("id_foto", id_foto) :
                new ObjectParameter("id_foto", typeof(int));
    
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergePoza", id_fotoParameter, id_preparatParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> StergePreparat(string denumire)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("StergePreparat", denumireParameter);
        }
    
        public virtual int StergePreparat2(Nullable<int> id_preparat)
        {
            var id_preparatParameter = id_preparat.HasValue ?
                new ObjectParameter("id_preparat", id_preparat) :
                new ObjectParameter("id_preparat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergePreparat2", id_preparatParameter);
        }
    
        public virtual int StergePreparatInMeniu(string denumireMeniu, string denumirePreparat)
        {
            var denumireMeniuParameter = denumireMeniu != null ?
                new ObjectParameter("denumireMeniu", denumireMeniu) :
                new ObjectParameter("denumireMeniu", typeof(string));
    
            var denumirePreparatParameter = denumirePreparat != null ?
                new ObjectParameter("denumirePreparat", denumirePreparat) :
                new ObjectParameter("denumirePreparat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergePreparatInMeniu", denumireMeniuParameter, denumirePreparatParameter);
        }
    
        public virtual int TrimiteComanda(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TrimiteComanda", emailParameter);
        }
    
        public virtual ObjectResult<VerificaContComanda_Result> VerificaContComanda(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VerificaContComanda_Result>("VerificaContComanda", emailParameter);
        }
    
        public virtual int stergePreparatDinCos(string denumire, Nullable<int> id_comanda)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stergePreparatDinCos", denumireParameter, id_comandaParameter);
        }
    
        public virtual int StergeMeniuDinCos(string denumire, Nullable<int> id_comanda)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StergeMeniuDinCos", denumireParameter, id_comandaParameter);
        }
    
        public virtual int ModificaStare(Nullable<int> id_comanda, Nullable<int> statusNou)
        {
            var id_comandaParameter = id_comanda.HasValue ?
                new ObjectParameter("id_comanda", id_comanda) :
                new ObjectParameter("id_comanda", typeof(int));
    
            var statusNouParameter = statusNou.HasValue ?
                new ObjectParameter("statusNou", statusNou) :
                new ObjectParameter("statusNou", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificaStare", id_comandaParameter, statusNouParameter);
        }
    }
}
