//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preparat()
        {
            this.AlergenPreparats = new HashSet<AlergenPreparat>();
            this.Fotografies = new HashSet<Fotografie>();
            this.MeniuPreparats = new HashSet<MeniuPreparat>();
            this.PreparatComandas = new HashSet<PreparatComanda>();
        }
    
        public int id_preparat { get; set; }
        public string denumire { get; set; }
        public Nullable<double> pret { get; set; }
        public Nullable<int> cantitate { get; set; }
        public Nullable<int> cantitate_totala { get; set; }
        public Nullable<int> id_categorie { get; set; }
        public string disponibilitate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlergenPreparat> AlergenPreparats { get; set; }
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotografie> Fotografies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeniuPreparat> MeniuPreparats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreparatComanda> PreparatComandas { get; set; }
    }
}
